name: Build Cereon Template Framework

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            preset: windows-msvc

          - os: windows-latest
            preset: windows-clang

          - os: ubuntu-latest
            preset: linux-gcc

          - os: ubuntu-latest
            preset: linux-clang

    steps:
      - uses: actions/checkout@v6

      - name: Setup MSVC
        if: matrix.os == 'windows-latest' && matrix.preset == 'windows-msvc'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup Clang
        if: contains(matrix.preset, 'clang')
        uses: egor-tensin/setup-clang@v2

      - name: Clean build dir
        run: rm -rf build/${{ matrix.preset }}
        shell: bash

      - name: Configure
        run: cmake --preset ${{ matrix.preset }} -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build/${{ matrix.preset }} --config Release --parallel